WIP: Add sonar pr decoration
philips-labs/sonar-scanner-action pull request #2
Opened 2020-04-11 09:43 UTC by npalm

2020-04-15 06:20 UTC, npalm commented
@PatrickMennen thanks for merging the two test files. But now the tests are not the same anymore. All tests are using now a context with the pull request payload.

2020-04-16 12:26 UTC, PatrickMennen reviewed
Your tests are failing at the moment

2020-04-16 12:26 UTC, PatrickMennen commented on README.MD
> +| scmPovider                  | SCM provider                                                             | no       | `git`   |
scmProvider -> typo

2020-04-16 12:26 UTC, PatrickMennen commented on src/sonarScanner-p.test.ts
> +jest.mock('@actions/github', () => ({
isn't this mock obsolete?

2020-04-16 12:27 UTC, PatrickMennen requested changes
getBranchOrTagName should not be inside the const and your unittests are failing at the moment.

2020-04-16 12:27 UTC, PatrickMennen commented on src/sonarScanner.ts
> +  function getBranchOrTagName(githubRef: string): string {
move outside of the function scope

2020-04-16 12:38 UTC, PatrickMennen approved these changes
Ok now!

2020-04-16 12:39 UTC, merged